export const ASTRO_QA_PAGES = [
  { name: 'home', path: '/' },
  { name: 'portfolio-index', path: '/portfolio/' },
  { name: 'caso-sofi', path: '/portfolio/sofi/' },
  { name: 'caso-heineken-green-challenge', path: '/portfolio/heineken-green-challenge/' },
  { name: 'caso-redux', path: '/portfolio/redux/' },
  { name: 'caso-hacksureste', path: '/portfolio/hacksureste/' },
  { name: 'caso-brain-mexico', path: '/portfolio/brain-mexico/' },
  { name: 'caso-btem-2021', path: '/portfolio/btem-2021/' },
  { name: 'caso-freeland', path: '/portfolio/freeland/' },
  { name: 'caso-g20-yea-model', path: '/portfolio/g20-yea-model/' },
  { name: 'caso-hacksureste-carmen-2019', path: '/portfolio/hacksureste-ciudad-del-carmen-2019/' },
  { name: 'caso-haz-que-pase-substack', path: '/portfolio/haz-que-pase-substack/' },
  { name: 'caso-idealab-hacksureste', path: '/portfolio/idealab-by-hacksureste/' },
  { name: 'caso-inc-prototype-2021', path: '/portfolio/inc-prototype-2021/' },
  { name: 'caso-incmty-accelerator-2021', path: '/portfolio/incmty-accelerator-2021/' },
  { name: 'caso-incmty-b-challenge-2021', path: '/portfolio/incmty-b-challenge-2021/' },
  { name: 'caso-incmty-disruptair-2022', path: '/portfolio/incmty-disruptair-challenge-2022/' },
  { name: 'politicas-privacidad', path: '/politicas-privacidad.html' },
  { name: 'terminos-y-condiciones', path: '/terminos-y-condiciones.html' },
  { name: '404', path: '/404.html' },
];
